<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="Test_Cases.Verify_dashboard" tests="8" time="142.544" ignored="0" failures="0" timestamp="20 Feb 2018 09:21:06 GMT" skipped="0" hostname="net04-PC" errors="1">
  <testcase name="Headerlinks" time="17.107" classname="Test_Cases.Verify_dashboard"/>
  <testcase name="verify_contact" time="0.062" classname="Test_Cases.Verify_dashboard"/>
  <testcase name="verify_quicklinks" time="38.377" classname="Test_Cases.Verify_dashboard"/>
  <testcase name="verify_cart" time="0.043" classname="Test_Cases.Verify_dashboard">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.pageObject.Home.verify_cart(Home.java:179)
	at Test_Cases.Verify_dashboard.verify_cart(Verify_dashboard.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verify_cart -->
  <testcase name="verify_resto" time="20.848" classname="Test_Cases.Verify_dashboard"/>
  <testcase name="verify_rights" time="0.051" classname="Test_Cases.Verify_dashboard"/>
  <testcase name="verify_location" time="12.019" classname="Test_Cases.Verify_dashboard"/>
  <testcase name="vefiry_banner" time="54.037" classname="Test_Cases.Verify_dashboard"/>
</testsuite> <!-- Test_Cases.Verify_dashboard -->
